[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "beanhand"
version = "0.8.1"
license = "GPL-3.0"
description = "AI-assisted CLI to help you work on your Beancount ledger"
requires-python = ">=3.14"
dependencies = ["openai>=2.0", "beancount>=3.2", "colorama>=0.4", "PyMuPDF>=1.27", "webdav4>=0.11", "httpx>=0.28", "certifi>=2025"]
readme = "README.md"

[project.urls]
Homepage = "https://github.com/Rudd-O/beanhand"
Repository = "https://github.com/Rudd-O/beanhand"
Issues = "https://github.com/Rudd-O/beanhand/issues"

[project.scripts]
beanhand-documents-server = "beanhand.server.documents.cli:main"
beanhand-ai-server = "beanhand.server.ai.cli:main"
beanhand = "beanhand.client.cli:main"
bh = "beanhand.client.cli:main"

[tool.setuptools.package-data]
"beanhand" = ["*.md"]
